# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpCli < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.1/mp_1.0.1_darwin_amd64.tar.gz"
      sha256 "b43e76669e6ad4c72c7daea2f2f5385d58c0566dd9d6c185cf7f6645cad635b5"

      define_method(:install) do
        begin
          Formula["mpcli"].unlink if Formula["mpcli"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mpcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.1/mp_1.0.1_darwin_arm64.tar.gz"
      sha256 "6456e19bcbdfbeedf4a331a01f8a104b50781fcdf90b69706f76a4aeeb68ac93"

      define_method(:install) do
        begin
          Formula["mpcli"].unlink if Formula["mpcli"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mpcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.1/mp_1.0.1_linux_amd64.tar.gz"
      sha256 "7fcf8c4b40fa9e5a9c7f5911d7e7fd101e8559a6394e7835f40af0f2f2d731e7"
      define_method(:install) do
        begin
          Formula["mpcli"].unlink if Formula["mpcli"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mpcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.1/mp_1.0.1_linux_arm64.tar.gz"
      sha256 "0822a29490be23cbab5ceb60e8eb003744f99b1fc39c07bc026417ef95dd587c"
      define_method(:install) do
        begin
          Formula["mpcli"].unlink if Formula["mpcli"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mpcli"
      end
    end
  end

  test do
    system "#{bin}/mpcli", "--version"
  end
end
