# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpCli < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_darwin_amd64.tar.gz"
      sha256 "6a1d38314a732c16f7879e437722cc3ff1504e81ba3163f5e329f31d211e75c1"

      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_darwin_arm64.tar.gz"
      sha256 "e2296f8e39a01a135c70d76569db9c79731240eb29d81ed7862c950d23dad327"

      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_linux_amd64.tar.gz"
      sha256 "f904a831b734c5fad786690c2bfe87f122606be23a108101a3f9ad265d9d2fb0"
      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_linux_arm64.tar.gz"
      sha256 "189335973005a576569c8476c550ee9353d14d4f8b9c78eb34c3b75bd22b281f"
      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "--version"
  end
end
