# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpCli < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_darwin_amd64.tar.gz"
      sha256 "54c773da423f86d0b4e85f77ca27939ab7fc98c4bca4d9fb48c4577d206162e5"

      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_darwin_arm64.tar.gz"
      sha256 "c4cf350282d99e9e2854e428a60786e8c1940774afe62bfac0397719b7485e97"

      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_linux_amd64.tar.gz"
      sha256 "264c8c2f5df6e8808824fab831f7b1f935c7cb300ede332c3d98e37ec042b254"
      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.0/mp_1.0.0_linux_arm64.tar.gz"
      sha256 "cfd887d4ac0b564f63cb5f2c860085cf6cc1e6e1d9990f8804a613b9e87ff723"
      define_method(:install) do
        begin
          Formula["mp"].unlink if Formula["mp"].linked?
        rescue FormulaUnavailableError
        end
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "--version"
  end
end
