# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v0.1.1/mp_0.1.1_darwin_amd64.tar.gz"
      sha256 "2583abd8650f2e226e277c385759590efa5fd2d94d0adce5cc1ea82a4e09952a"

      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v0.1.1/mp_0.1.1_darwin_arm64.tar.gz"
      sha256 "7a9af2effcc391e831dd95206ccc970be639b517952d2da6f45583c8471136d0"

      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v0.1.1/mp_0.1.1_linux_amd64.tar.gz"
      sha256 "50c7dbcdc194579a3d85d9d125d26a3c9c795988bdbfdb1b8bc467cc71fa081d"
      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v0.1.1/mp_0.1.1_linux_arm64.tar.gz"
      sha256 "a2b8208b49856e15fb6b132e495242ade6a73984b3e7d385063c90d73850668c"
      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "--version"
  end
end
