# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/mp-cli/releases/download/v0.1.0/mp_0.1.0_darwin_amd64.tar.gz"
      sha256 "bab3e70972adae2bc5b52c7f4f49d22a0fbbad10edaf728006ab3112a56b1389"

      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/mp-cli/releases/download/v0.1.0/mp_0.1.0_darwin_arm64.tar.gz"
      sha256 "db76a1bc94d792d0e827ddcae80f772f9fa593a8effe7859e5ee04ee70d6cde9"

      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/mp-cli/releases/download/v0.1.0/mp_0.1.0_linux_amd64.tar.gz"
      sha256 "60a0265068ccbcc136d821554c888f7847132a87affd31f49dd7a60d297fdca7"
      define_method(:install) do
        bin.install "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/mp-cli/releases/download/v0.1.0/mp_0.1.0_linux_arm64.tar.gz"
      sha256 "28dd49659ffd68e360046d815bb8b30af7f57e24b45897183e383d62edd37822"
      define_method(:install) do
        bin.install "mp"
      end
    end
  end

  test do
    system "#{bin}/mp", "--version"
  end
end
