# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpcli < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.3/mp_1.0.3_darwin_amd64.tar.gz"
      sha256 "27b4970efd635cefad3d09ff937704279bfbf68857ced208f42aee082947d198"

      define_method(:install) do
        bin.install "mpcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.3/mp_1.0.3_darwin_arm64.tar.gz"
      sha256 "47c6c566419a482bc1279d76b3f758dea839fadb71b97362e0ce48765876736a"

      define_method(:install) do
        bin.install "mpcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.3/mp_1.0.3_linux_amd64.tar.gz"
      sha256 "b0107410a0092f83edffa1744f12439613ae07dd2c549b2a970fef9db36bf1cd"
      define_method(:install) do
        bin.install "mpcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.3/mp_1.0.3_linux_arm64.tar.gz"
      sha256 "97028258f3b802da8cca705d9a267157e877985fcac81eccd3a140d0988658f6"
      define_method(:install) do
        bin.install "mpcli"
      end
    end
  end

  test do
    system "#{bin}/mpcli", "--version"
  end
end
