# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpcli < Formula
  desc "The official Mercado Pago CLI for developers and AI agents."
  homepage "https://github.com/mercadopago/mp-cli"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.2/mp_1.0.2_darwin_amd64.tar.gz"
      sha256 "ecf615f43f12e5d067265e43bd661b59a43b91f5a7a33d2fd15a2ff92843044a"

      define_method(:install) do
        bin.install "mpcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.2/mp_1.0.2_darwin_arm64.tar.gz"
      sha256 "0c32702471a60f6a1f0890585b2954ccb43e748d8dbf428701d694b660e213aa"

      define_method(:install) do
        bin.install "mpcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.2/mp_1.0.2_linux_amd64.tar.gz"
      sha256 "ccf27345c5528c8648a79ceaeed24a4e24a42cb9db31e7a21b85db3e00ff46f3"
      define_method(:install) do
        bin.install "mpcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mercadopago/homebrew-tap/releases/download/v1.0.2/mp_1.0.2_linux_arm64.tar.gz"
      sha256 "4930e7cb0d5c8cb288eda8e41d9862f81452cae739a1e767526527dcf6ee0a7e"
      define_method(:install) do
        bin.install "mpcli"
      end
    end
  end

  test do
    system "#{bin}/mpcli", "--version"
  end
end
